version: '3'
services:
  app:
    build: ./app
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
  aframe_generator:
    build: ./aframe_generator
    entrypoint: npm index.js
    ports:
      - "3000:3000"
    volumes:
      - ./aframe_generator:/home/node/html
      - /home/node/html/node_modules
  service_snapshot:
    build: ./service_snapshot
    entrypoint: npm start
    ports:
      - "3001:3000"
    volumes: 
      - ./service_snapshot:/home/node/html
      - service_snapshot_nodemodules:/home/node/html/node_modules

volumes:
  service_snapshot_nodemodules: